Regions = new Mongo.Collection("regions");

Meteor.startup(function () {
    if(Regions.find({}).count()<=0){
     Regions.insert({"code":"10","name":"Aube"});
     Regions.insert({"code":"11","name":"Aude"});
     Regions.insert({"code":"12","name":"Aveyron"});
     Regions.insert({"code":"13","name":"Bouches-du-Rhône"});
     Regions.insert({"code":"14","name":"Calvados"});
     Regions.insert({"code":"15","name":"Cantal"});
     Regions.insert({"code":"16","name":"Charente"});
     Regions.insert({"code":"17","name":"Charente Maritime"});
     Regions.insert({"code":"18","name":"Cher"});
     Regions.insert({"code":"19","name":"Corrèze"});
     Regions.insert({"code":"21","name":"Côte d'Or"});
     Regions.insert({"code":"22","name":"Côtes d'Armor"});
     Regions.insert({"code":"23","name":"Creuse"});
     Regions.insert({"code":"24","name":"Dordogne"});
     Regions.insert({"code":"25","name":"Doubs"});
     Regions.insert({"code":"26","name":"Drôme"});
     Regions.insert({"code":"27","name":"Eure"});
     Regions.insert({"code":"28","name":"Eure-et-Loir"});
     Regions.insert({"code":"29","name":"Finistère"});
     Regions.insert({"code":"30","name":"Gard"});
     Regions.insert({"code":"31","name":"Haute Garonne"});
     Regions.insert({"code":"32","name":"Gers"});
     Regions.insert({"code":"33","name":"Gironde"});
     Regions.insert({"code":"34","name":"Hérault"});
     Regions.insert({"code":"35","name":"Ille et Vilaine"});
     Regions.insert({"code":"36","name":"Indre"});
     Regions.insert({"code":"37","name":"Indre et Loire"});
     Regions.insert({"code":"38","name":"Isère"});
     Regions.insert({"code":"39","name":"Jura"});
     Regions.insert({"code":"40","name":"Landes"});
     Regions.insert({"code":"41","name":"Loir-et-Cher"});
     Regions.insert({"code":"42","name":"Loire"});
     Regions.insert({"code":"43","name":"Haute Loire"});
     Regions.insert({"code":"44","name":"Loire Atlantique"});
     Regions.insert({"code":"45","name":"Loiret"});
     Regions.insert({"code":"46","name":"Lot"});
     Regions.insert({"code":"47","name":"Lot et Garonne"});
     Regions.insert({"code":"48","name":"Lozère"});
     Regions.insert({"code":"49","name":"Maine et Loire"});
     Regions.insert({"code":"50","name":"Manche"});
     Regions.insert({"code":"51","name":"Marne"});
     Regions.insert({"code":"52","name":"Haute Marne"});
     Regions.insert({"code":"53","name":"Mayenne"});
     Regions.insert({"code":"54","name":"Meurthe et Moselle"});
     Regions.insert({"code":"55","name":"Meuse"});
     Regions.insert({"code":"56","name":"Morbihan"});
     Regions.insert({"code":"57","name":"Moselle"});
     Regions.insert({"code":"58","name":"Nièvre"});
     Regions.insert({"code":"59","name":"Nord"});
     Regions.insert({"code":"60","name":"Oise"});
     Regions.insert({"code":"61","name":"Orne"});
     Regions.insert({"code":"62","name":"Pas-de-Calais"});
     Regions.insert({"code":"63","name":"Puy de Dôme"});
     Regions.insert({"code":"64","name":"Pyrénées Atlantiques"});
     Regions.insert({"code":"65","name":"Hautes Pyrénées"});
     Regions.insert({"code":"66","name":"Pyrénées Orientales"});
     Regions.insert({"code":"67","name":"Bas Rhin"});
     Regions.insert({"code":"68","name":"Haut Rhin"});
     Regions.insert({"code":"69","name":"Rhône"});
     Regions.insert({"code":"70","name":"Haute Saône"});
     Regions.insert({"code":"71","name":"Saône et Loire"});
     Regions.insert({"code":"72","name":"Sarthe"});
     Regions.insert({"code":"73","name":"Savoie"});
     Regions.insert({"code":"74","name":"Haute Savoie"});
     Regions.insert({"code":"75","name":"Paris"});
     Regions.insert({"code":"76","name":"Seine Maritime"});
     Regions.insert({"code":"77","name":"Seine et Marne"});
     Regions.insert({"code":"78","name":"Yvelines"});
     Regions.insert({"code":"79","name":"Deux Sèvres"});
     Regions.insert({"code":"80","name":"Somme"});
     Regions.insert({"code":"81","name":"Tarn"});
     Regions.insert({"code":"82","name":"Tarn et Garonne"});
     Regions.insert({"code":"83","name":"Var"});
     Regions.insert({"code":"84","name":"Vaucluse"});
     Regions.insert({"code":"85","name":"Vendée"});
     Regions.insert({"code":"86","name":"Vienne"});
     Regions.insert({"code":"87","name":"Haute Vienne"});
     Regions.insert({"code":"88","name":"Vosges"});
     Regions.insert({"code":"89","name":"Yonne"});
     Regions.insert({"code":"90","name":"Territoire de Belfort"});
     Regions.insert({"code":"91","name":"Essonne"});
     Regions.insert({"code":"92","name":"Hauts de Seine"});
     Regions.insert({"code":"93","name":"Seine St Denis"});
     Regions.insert({"code":"94","name":"Val de Marne"});
     Regions.insert({"code":"95","name":"Val d'Oise"});
     Regions.insert({"code":"971","name":"Guadeloupe"});
     Regions.insert({"code":"972","name":"Martinique"});
     Regions.insert({"code":"973","name":"Guyane"});
     Regions.insert({"code":"974","name":"La Réunion"});
     Regions.insert({"code":"02","name":"Aisne"});
     Regions.insert({"code":"07","name":"Ardèche"});
     Regions.insert({"code":"01","name":"Ain"});
     Regions.insert({"code":"04","name":"Alpes de Haute Provence"});
     Regions.insert({"code":"05","name":"Hautes Alpes"});
     Regions.insert({"code":"08","name":"Ardennes"});
     Regions.insert({"code":"03","name":"Allier"});
     Regions.insert({"code":"09","name":"Ariège"});
     Regions.insert({"code":"06","name":"Alpes Maritimes"});
     Regions.insert({"code":"2B","name":"Haute Corse"});
     Regions.insert({"code":"2A","name":"Corse du Sud"});

     }

});